name: Test

on:
  # Trigger the workflow on push or pull request, but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Trigger the workflow at the end of every week
  schedule:
    - cron: '0 0 * * 0'
  # Trigger the workflow when it is manually triggered
  workflow_dispatch:


jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        compiler: [gcc]
        version: [11, 10, 9, 8]
        bitness: [32, 64]
        manylinux_image: [manylinux1, manylinux2010, manylinux2014, manylinux_2_24]
        include:
          # Run 32- and 64-bit versions in parallel for Linux
          # MacOS 10.14 Mojave is the last version that supports 32-bit software
          - os: ubuntu-latest
            bitness: 64
            platform_id: manylinux_x86_64
          - os: ubuntu-latest
            bitness: 32
            platform_id: manylinux_i686
          - os: macos-latest
            bitness: 64
            platform_id: macosx_x86_64
          - os: windows-latest
            bitness: 32
            platform_id: win_i686
          - os: windows-latest
            bitness: 64
            platform_id: win_amd64
        exclude:
          # manylinux_image is not used on Windows and macOS
          - os: macos-latest
            bitness: 32
          - os: macos-latest
            manylinux_image: manylinux2010
          - os: macos-latest
            manylinux_image: manylinux2014
          - os: macos-latest
            manylinux_image: manylinux_2_24
            #- os: windows-latest
            #bitness: 32
          - os: windows-latest
            manylinux_image: manylinux2010
          - os: windows-latest
            manylinux_image: manylinux2014
          - os: windows-latest
            manylinux_image: manylinux_2_24

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Fortran
        id: setup_fortran
        # Use the action defined at github.com/zaikunzhang/setup-fortran to setup Fortran
        uses: zaikunzhang/setup-fortran@main
        with:
          compiler: ${{ matrix.compiler }}
          version: ${{ matrix.version }}

      - name: Check Fortran compiler
        run: |
          ${{ env.FC }} --version
          ${{ env.CC }} --version
        shell: bash
        env:
          FC: ${{ steps.setup_fortran.outputs.fc }}
          CC: ${{ steps.setup_fortran.outputs.cc }}

      - name: Conduct the test
        run: |
          cd test; make gtest
