name: Test gfortran

on:
  # Trigger the workflow on push or pull request
  push:
  pull_request:
  # Trigger the workflow at the end of every week
  schedule:
    - cron: '0 0 * * 0'
  # Trigger the workflow when it is manually triggered
  workflow_dispatch:


jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, macos-latest, macos-11, windows-latest, windows-2019]
        compiler: [gcc]
        version: [13, 12, 11, 10]
        exclude:
          - os: ubuntu-20.04
            version: 12
          - os: ubuntu-20.04
            version: 13
          - os: windows-latest
            version: 13
          - os: windows-2019
            version: 13

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.0
        with:
         ssh-key: ${{ secrets.SSH_PRIVATE_KEY_ACT }} # This forces checkout to use SSH, not HTTPS
         submodules: recursive

      - name: Setup Fortran
        id: setup_fortran
        # Use the action defined at github.com/awvwgk/setup-fortran@main to setup Fortran
        uses: awvwgk/setup-fortran@main
        with:
          compiler: ${{ matrix.compiler }}
          version: ${{ matrix.version }}

      - name: Check Fortran compiler
        run: |
          ${{ env.FC }} --version
          ${{ env.CC }} --version
        shell: bash
        env:
          FC: ${{ steps.setup_fortran.outputs.fc }}
          CC: ${{ steps.setup_fortran.outputs.cc }}

      - name: Conduct the test
        run: cd test; make gtest
