name: Test gfortran

on:
  # Trigger the workflow on push or pull request
  push:
  pull_request:
  # Trigger the workflow at the end of every week
  schedule:
    - cron: '0 0 * * 0'
  # Trigger the workflow when it is manually triggered
  workflow_dispatch:


jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        compiler: [gcc]
        version: [11, 10, 9, 8]
        bitness: [32, 64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Fortran
        id: setup_fortran
        # Use the action defined at github.com/zaikunzhang/setup-fortran to setup Fortran
        uses: zaikunzhang/setup-fortran@main
        with:
          compiler: ${{ matrix.compiler }}
          version: ${{ matrix.version }}

      - name: Check Fortran compiler
        run: |
          ${{ env.FC }} --version
          ${{ env.CC }} --version
        shell: bash
        env:
          FC: ${{ steps.setup_fortran.outputs.fc }}
          CC: ${{ steps.setup_fortran.outputs.cc }}

      - name: Conduct the test
        run: |
          cd test; make gtest
