name: Test NAG Fortran compiler

on:
  # Trigger the workflow on push or pull request
  push:
  # pull_request:  # Disable this on self-hosted runners!!!
  # Trigger the workflow by cron. The default time zone of GitHub Actions is UTC.
  schedule:
    - cron: '0 0 * * 0'
  # Trigger the workflow when it is manually triggered
  workflow_dispatch:

jobs:
  test:
    name: Run the tests
    runs-on: [self-hosted, nagfor]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.4
        with:
         ssh-key: ${{ secrets.SSH_PRIVATE_KEY_ACT }} # This forces checkout to use SSH, not HTTPS
         submodules: recursive

      - name: Conduct the test
        run: |
          export PATH=$PATH:"~/local/bin"
          source ~/local/bin/nag_licensing || echo "\n\nNAG licensing failed.\n\n"
          cd test && make ntest
