name: Test compilers on Kunpeng

on:
  # Trigger the workflow on push or pull request
  push:
  # pull_request:  # Disable this on self-hosted runners!!!
  # Trigger the workflow at the end of every week
  schedule:
    - cron: '0 0 * * 0'
  # Trigger the workflow when it is manually triggered
  workflow_dispatch:


jobs:
  test:
    runs-on: [self-hosted, kp, ARM64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0
        with:
         submodules: recursive

      - name: Conduct the test
        run: |
          ARMDIR="$(find /opt/arm -maxdepth 1 -name "arm-linux-compiler*" -type d -print | sort | tail -n 1)"
          if [[ -n "$ARMDIR" ]] ; then
            export PATH=$PATH:"$ARMDIR"/bin
            export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
  -         ARMLD="$(find /opt/arm -type f -executable -name ld | xargs dirname)"
            ARMLD_DIR=${ARMLD//$'\n'/:}
            export PATH=$PATH:"$ARMLD_DIR"
          fi
          cd test && make gtest && make clean && make ftest && make clean && make rtest
